services:
  postgres:
    image: postgres:16.4
    container_name: postgres-test
    environment:
      POSTGRES_DB: orv_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "4321:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
