services:
  api:
    image: chj7239/orv-api-server:staging
    container_name: orv_api_server
    ports:
      - "80:8080"
    env_file:
      - .env.staging
    depends_on:
      - postgres

  nginx:
    build: nginx
    container_name: orv_nginx
    ports:
      - "443:443"
    depends_on:
      - api

  postgres:
    image: postgres:16.4
    container_name: orv_postgres
    environment:
      POSTGRES_DB: orv_staging
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "4321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
